export var strategy_closer = "The strategy used by closers can capture only one percent of the total pottential market. They are most suitable to sell gateswingers who buy technology of the 'birth' type. During market entry, expect an ice-cold reaction from most. But if you have the right product, the energy and the drive, and the capital to go the distance; this is an auspicious phase of the market cycle to start a business. There is little or no direct competition. One can own the market for a time. Core selling strategy: Build the dream. Play to the customer's fantasy and desires. Use excitement to conquer the customer's fear."


export var strategy_wizard = "The strategy used by wizards/ sales-engineer can caputre upto 20 percent of the total pottential market. They are most suitable to sell to progressive customers who buy technology of the fast growth type. During market entry, expect the cool response from most prospects. A cutting edge technology that is developed and sophisticated is needed. Some will welcome the new capability and technology, but many will question the necessity of it, or will object to the cost involved. Core selling strategy: Knowledge is the most important asset, which is used to create custom solutions and individualise systems for the customers."


export var strategy_relationshipbuilder = "The strategy is used by a relationshipbuilder, can capture upto 70 percent of the market. They are most suitable to sell to the 'relationship customer' type. During market entry, there is plenty of competition especially from those selling almost similar products. As the market has warmed up, lots of sellers want a piece of it. A good niche is required to succeed that others may have overlooked. Core selling strategy: Be the customer's strongest ally. Work for solid relationships based on creative problem solving, dependable delivery, personalised attention to details. The customer is charged according to the added value delivered through the sales force."


export var strategy_crew = "The strategy used by a crew sales team and its captain, can capture upto 94 percent of the total market, while remaining 6 percent are new entries and others who need extra support. During market entry, if it is a new business, there will be a long uphill battle agains established competition. Usually this type of market is dominated by three or four major suppliers with organisations large enough to have economies of scale. Core selling strategy: Make it easy to buy. Strive to eliminate barriers to the sale. Give customers low price, easy credit, no-hassles service."
