var birth = "The 'birth' type of technology is new and revolutionary yet primitive. Products are capable of only basic tasks and have few if any features or options. During this period of infancy, apeal and value are limited to a relatively small number of people; but if the technology is successful, those few quickly become enthisiasts. As an example, when the wheel is invented, it is at this 'birth' stage initially. The customers don't yet know about the wheel until the salesperson introduces it."


var fast_growth = "As the technology advances, it becomes the type 'fast growth'. This advance often happens dramatically and in big jumps. However, witht the advancement, there is an increase in options available and the complexity of the technology. Implimentation of the technology often involves custom-tailoring to each buyer's special needs. Though now more valuable to a broader range of people, the technology still has many skeptics. When the wheel has been sold. As an example, after the stone wheel has been bought and used by a few gateswinger enthusiasts, and new wooden and spoked wheels are introduced; or the stone wheel starts to be used for grinding."


var incremantal_growth = "After the technology has passed the phase of 'fast growth', it goes into widespread use. Thus follows the type of 'incremental growth' technology. The market penetration increases and the technology becomes accepted by majority of the pottential market. While it continues advancement, improvements come in smaller, less dramatic steps. Products in this type of incremental growth become feature-rich and avaialable options become a marketing tool. Those who buy and use these products are familiary with performance issues and can hold informed coversations about them, often to the irritation of the dwindling number of holdouts. As an example, when the wheel has passed the phase of fast growth and has been used in at least a major project, that catches the eye of other businesses, it moves into widespread use and the stage of 'incremental growth'."


var maturity = "After the technology has been used widely, it is standardised and reches the stage of type 'maturity'. It has near universal acceptance within the culture, one is considered eccentric if you do not use it. Advancements are few and might be met with resistance. The choices regarding features and option are reduced as they become standard to the essential product. Products are simple to use, even 'idiot-proof'. However, this causes the technology to become frozen; thereby creating opportunities for the next technological wave that will force its obsolescence, and disrupt the market. As an example, when wooden wheels have become standardized and used by everyone in all sorts of transportation activities. It may be disrupted by the introdcution of newer rubber wheels in the future."

export var technologies = [birth, fast_growth, incremantal_growth, maturity];
